version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: "git"
    directory: "/"
    schedule:
      interval: "weekly"  # Lebih aman untuk submodule
    labels:
      - "dependencies"
      - "submodules"
    commit-message:
      prefix: "chore(deps)"
